### ISSUE TITLE
ignore polls from previous years

### ISSUE THREAD

**Issue by stephens999** [georgeberry/simple_polls#2]
don't you want to only focus on polls from 2016? 
At present your code includes doy, say > 310 that are from previous years, not this year.

eg make the change:

`df = read.csv('polls.csv')`
`df$year = as.numeric(substr(df$start_date,1,4))`
`df = df[df$year == 2016,]`

in analysis.R ??

**Comment by georgeberry** [comment]
Good catch, code updated.
